# -*- coding: utf-8 -*-
"""TrabalhoIII.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CC3WFSXNykqw3iSL9xmv6CVnK4mNLj1j
"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn import metrics
import seaborn as sn
import matplotlib.pyplot as plt
import numpy as np

data =  pd.read_csv("./treino_eletro.csv")
print(data)

def str_to_complex(str_complex):
    str_complex = str_complex.strip('()')
    complex_t = complex(str_complex)
    return complex_t

def convert_dataframe_to_t(df):
    for col in df.columns:
        if type(df[col][0]) == str:
          df[col] = df[col].apply(str_to_complex)

    return df

data = convert_dataframe_to_t(data)

data

X = data.drop(['resultado'], axis=1)
y = data['resultado']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

logistic_regression= LogisticRegression()
logistic_regression.fit(X_train,y_train)
y_pred=logistic_regression.predict(X_test)

confusion_matrix = pd.crosstab(y_test, y_pred, rownames=['Actual'], colnames=['Predicted'])
sn.heatmap(confusion_matrix, annot=True)

print('Accuracy: ',metrics.accuracy_score(y_test, y_pred))
plt.show()